const PERMISSIONS = {
  // DASHBOARD
  DASHBOARD_ACCESS: "DASHBOARD_ACCESS",

  // PROFILE
  PROFILE_ACCESS: "PROFILE_ACCESS",

  // ROLES / PERMISSIONS MANAGEMENT
  MANAGE_ROLES: "MANAGE_ROLES",
  MANAGE_PERMISSIONS: "MANAGE_PERMISSIONS",
  MANAGE_USER_ACCESS: "MANAGE_USER_ACCESS",

  // ITEMS
  ITEM_MODULE: "ITEM_MODULE",
  VIEW_ITEM: "VIEW_ITEM",
  ADD_ITEM: "ADD_ITEM",
  EDIT_ITEM: "EDIT_ITEM",
  DELETE_ITEM: "DELETE_ITEM",

  // PURCHASE
  PURCHASE_MODULE: "PURCHASE_MODULE",
  VIEW_PURCHASE: "VIEW_PURCHASE",
  CREATE_PURCHASE: "CREATE_PURCHASE",
  EDIT_PURCHASE: "EDIT_PURCHASE",
  DELETE_PURCHASE: "DELETE_PURCHASE",
  PRINT_PURCHASE: "PRINT_PURCHASE",
  DOWNLOAD_PURCHASE_PDF: "DOWNLOAD_PURCHASE_PDF",

  // INVOICE
  INVOICE_MODULE: "INVOICE_MODULE",
  VIEW_INVOICE: "VIEW_INVOICE",
  CREATE_INVOICE: "CREATE_INVOICE",
  EDIT_INVOICE: "EDIT_INVOICE",
  BULK_INVOICE: "BULK_INVOICE",
  CHNAGE_INVOICE_DATE: "CHNAGE_INVOICE_DATE",
  DELETE_INVOICE: "DELETE_INVOICE",
  PRINT_INVOICE: "PRINT_INVOICE",
  DOWNLOAD_INVOICE_PDF: "DOWNLOAD_INVOICE_PDF",

  // CUSTOMERS
  CUSTOMER_MODULE: "CUSTOMER_MODULE",
  VIEW_CUSTOMER: "VIEW_CUSTOMER",
  ADD_CUSTOMER: "ADD_CUSTOMER",
  EDIT_CUSTOMER: "EDIT_CUSTOMER",
  DELETE_CUSTOMER: "DELETE_CUSTOMER",

  // PAYMENTS
  PAYMENT_MODULE: "PAYMENT_MODULE",
  VIEW_PAYMENT: "VIEW_PAYMENT",
  ADD_PAYMENT: "ADD_PAYMENT",
  DELETE_PAYMENT: "DELETE_PAYMENT",

  // REPORTS
  REPORT_MODULE: "REPORT_MODULE",
  VIEW_REPORT: "VIEW_REPORT",
  EXPORT_REPORT: "EXPORT_REPORT",

  // EXPENSES
  EXPENSE_MODULE: "EXPENSE_MODULE",
  VIEW_EXPENSE: "VIEW_EXPENSE",
  CREATE_EXPENSE: "CREATE_EXPENSE",
  DELETE_EXPENSE: "DELETE_EXPENSE",

  // ACCOUNTS
  ACCOUNT_MODULE: "ACCOUNT_MODULE",
  VIEW_ACCOUNT: "VIEW_ACCOUNT",
  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  DELETE_ACCOUNT: "DELETE_ACCOUNT",

  // VOUCHERS
  VOUCHER_MODULE: "VOUCHER_MODULE",
  VIEW_VOUCHER: "VIEW_VOUCHER",
  CREATE_VOUCHER: "CREATE_VOUCHER",
  DELETE_VOUCHER: "DELETE_VOUCHER",

  // STOCK
  STOCK_MODULE: "STOCK_MODULE",
  VIEW_STOCK: "VIEW_STOCK",

  // USERS
  USER_MODULE: "USER_MODULE",
  VIEW_USER: "VIEW_USER",
  ADD_USER: "ADD_USER",
  EDIT_USER: "EDIT_USER",
  DELETE_USER: "DELETE_USER",

  // LEDGER
  CUSTOMER_LEDGER: "CUSTOMER_LEDGER",
};

module.exports = PERMISSIONS;
