const PERMISSIONS = {
  // DASHBOARD
  DASHBOARD_ACCESS: "DASHBOARD_ACCESS",

  // ROLES / PERMISSIONS MANAGEMENT
  MANAGE_ROLES: "MANAGE_ROLES",
  MANAGE_PERMISSIONS: "MANAGE_PERMISSIONS",
  MANAGE_USER_ACCESS: "MANAGE_USER_ACCESS",

  // ITEMS
  ITEMS_MODULE: "ITEMS_MODULE",
  VIEW_ITEMS: "VIEW_ITEMS",
  ADD_ITEM: "ADD_ITEM",
  EDIT_ITEM: "EDIT_ITEM",
  DELETE_ITEM: "DELETE_ITEM",

  // PURCHASE
  PURCHASE_MODULE: "PURCHASE_MODULE",
  VIEW_PURCHASE: "VIEW_PURCHASE",
  CREATE_PURCHASE: "CREATE_PURCHASE",
  EDIT_PURCHASE: "EDIT_PURCHASE",
  DELETE_PURCHASE: "DELETE_PURCHASE",
  PRINT_PURCHASE: "PRINT_PURCHASE",
  DOWNLOAD_PURCHASE_PDF: "DOWNLOAD_PURCHASE_PDF",

  // INVOICE
  INVOICE_MODULE: "INVOICE_MODULE",
  VIEW_INVOICE: "VIEW_INVOICE",
  CREATE_INVOICE: "CREATE_INVOICE",
  EDIT_INVOICE: "EDIT_INVOICE",
  CHNAGE_INVOICE_DATE: "CHNAGE_INVOICE_DATE",
  DELETE_INVOICE: "DELETE_INVOICE",
  PRINT_INVOICE: "PRINT_INVOICE",
  DOWNLOAD_INVOICE_PDF: "DOWNLOAD_INVOICE_PDF",

  // CUSTOMERS
  CUSTOMERS_MODULE: "CUSTOMERS_MODULE",
  VIEW_CUSTOMERS: "VIEW_CUSTOMERS",
  ADD_CUSTOMER: "ADD_CUSTOMER",
  EDIT_CUSTOMER: "EDIT_CUSTOMER",
  DELETE_CUSTOMER: "DELETE_CUSTOMER",

  // PAYMENTS
  PAYMENTS_MODULE: "PAYMENTS_MODULE",
  VIEW_PAYMENTS: "VIEW_PAYMENTS",
  ADD_PAYMENT: "ADD_PAYMENT",

  // REPORTS
  REPORTS_MODULE: "REPORTS_MODULE",

  // EXPENSES
  EXPENSES_MODULE: "EXPENSES_MODULE",

  // ACCOUNTS
  ACCOUNTS_MODULE: "ACCOUNTS_MODULE",

  // VOUCHERS
  VOUCHERS_MODULE: "VOUCHERS_MODULE",

  // STOCK
  STOCK_MODULE: "STOCK_MODULE",

  // USERS
  USERS_MODULE: "USERS_MODULE",
  VIEW_USERS: "VIEW_USERS",
  ADD_USER: "ADD_USER",
  EDIT_USER: "EDIT_USER",
  DELETE_USER: "DELETE_USER",

  // LEDGER
  CUSTOMER_LEDGER: "CUSTOMER_LEDGER",
};

module.exports = PERMISSIONS;
